### ISSUE TITLE
make a release V0

### ISSUE THREAD

**Issue by joe9599** [sourcebots/camera-board-hw#3]
the prototype that was made should be our first release, so that we know what stage it was at when it was made

**Comment by trickeydan** [comment]
This should be done using a GitHub release.

On the main page of the repo, click on releases and then "Draft Release".

You can then add a description, version number etc. Make sure to select the commit of the version that we manufactured.

**Comment by joe9599** [comment]
Yeah, that's what I was going to do, but didn't have access

**Comment by trickeydan** [comment]
Query: Why `v0`? Surely it makes more sense to start at Rev 1?

**Comment by joe9599** [comment]
I was thinking 0 as it is a non working protoype

**Comment by trickeydan** [comment]
Have done some research:

```
We handle it the following way: Major.Minor.Revision

Major is changed, if there were changes to board dimensions or extensive changes to component placement or general functionality. Like re-designing a PCB for a different enclosure or adding a new connector.

Minor is changed, if there were any changes to component placement, routing, copper fills etc. Essentially any change, that potentially changes electrical characteristics.

Revision represents the revision number from our version control system (Subversion) and thus increases with every committed change. This could be a small change to the silkscreen or changing component types/values due to better availability. Versions with a revision changes only can be processed by the assembly house without any adjustments (paste mask compatible, same dimensions, same pick&place).

Version progression: If Major is incremented, Minor resets to 0. Revisions always increments and unambiguously identifies a specific version. Example: 1.0.0 -> 1.0.1 -> 1.0.2 -> 1.1.3 -> 2.0.4

Relevance to part list: Our BOM contains a reference to the Major.Minor version of the compatible target PCB. The revision is not relevant with respect to the PCB, since there were no relevant physical changes. Thus, 1.2.10 can be assembled just like 1.2.15. The BOM itself has a revision number, that is equal or higher than the target PCB version. Example: A BOM titled "BOM 1.2.18 - Target PCB 1.2" can be used to assemble boards of version 1.2.10 as well as 1.2.15.
```

I think this summarises a good scheme for naming board revisions. However it doesn't solve the thing we're discussing. I'd be happy with a `v0.0.1` etc.

**Comment by joe9599** [comment]
The way we do it at work is major.minor, major is incremented when something is to be shipped, else minor is incremented, but that adds an unnecessary step of changing silkscreen anytime we want to commit anything, as the version number should be printed on the pc 
In the above case, the minor I described is the same as your revision, and major combines your major and minor (I think this is better, because especially with the camera board, the way it's routed is a major change, due to time critical traces)

**Comment by joe9599** [comment]
Ultimately we can figure out the details later, I just want to work on the next version, so need to make a release so that we know the state of the design at this build
